#!/bin/bash
# File Converter GUI Integration Setup Script
# Filename: setup_gui.sh
# Version 4.1
# Sets up Nautilus integration and desktop entries for File Converter

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"  # Scripts are in the same directory as gui.py
FILE_CONVERTER_SCRIPT="$PROJECT_ROOT/gui.py"
EXTENSION_SRC="$PROJECT_ROOT/file_converter_extension.py"
NAUTILUS_EXTENSION_DIR="$HOME/.local/share/nautilus-python/extensions"
NAUTILUS_EXTENSION_LINK="$NAUTILUS_EXTENSION_DIR/file_converter_extension.py"
NEMO_EXTENSION_DIR="$HOME/.local/share/nemo-python/extensions"
NEMO_EXTENSION_LINK="$NEMO_EXTENSION_DIR/file_converter_extension.py"
NAUTILUS_SCRIPT_DIR="$HOME/.local/share/nautilus/scripts"
NEMO_SCRIPT_DIR="$HOME/.local/share/nemo/scripts"

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
} 

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
} 

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
} 

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
} 

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
} 

# Function to detect desktop environment
detect_desktop() {
    if [ "$XDG_CURRENT_DESKTOP" = "GNOME" ] || [ "$DESKTOP_SESSION" = "gnome" ]; then
        echo "gnome"
    elif [ "$XDG_CURRENT_DESKTOP" = "X-Cinnamon" ] || [ "$XDG_CURRENT_DESKTOP" = "Cinnamon" ] || [ "$DESKTOP_SESSION" = "cinnamon" ]; then
        echo "cinnamon"
    elif [ "$XDG_CURRENT_DESKTOP" = "KDE" ] || [ "$DESKTOP_SESSION" = "kde" ]; then
        echo "kde"
    elif [ "$XDG_CURRENT_DESKTOP" = "XFCE" ] || [ "$DESKTOP_SESSION" = "xfce" ]; then
        echo "xfce"
    else
        echo "unknown"
    fi
} 

# Install the basic right-click "Convert with File Converter" script for each
# detected file manager (Nautilus on GNOME, Nemo on Cinnamon). The same script
# body works under both because it falls back between the two env vars they use
# to expose the selection.
setup_fm_integration() {
    print_status "Setting up file manager right-click script..."

    local tmpscript
    tmpscript="$(mktemp)"
    cat > "$tmpscript" << 'FM_SCRIPT_EOF'
#!/bin/bash
# Right-click script: Convert with File Converter
# Auto-generated by File Converter setup. Works under Nautilus and Nemo.

FILE_CONVERTER_PATH="FILE_CONVERTER_PATH_PLACEHOLDER"
PYTHON_CMD="python3"

show_error() {
    if command -v zenity >/dev/null 2>&1; then
        zenity --error --text="$1" --width=300
    else
        echo "Error: $1" >&2
    fi
}

if [ ! -f "$FILE_CONVERTER_PATH" ]; then
    show_error "File Converter not found at: $FILE_CONVERTER_PATH"
    exit 1
fi

# Nautilus exposes selection via NAUTILUS_SCRIPT_SELECTED_FILE_PATHS;
# Nemo via NEMO_SCRIPT_SELECTED_FILE_PATHS. Same newline-separated format.
FILES="${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS:-$NEMO_SCRIPT_SELECTED_FILE_PATHS}"

if [ -z "$FILES" ]; then
    show_error "No file selected. Please select a file to convert and try again."
    exit 1
fi

IFS=$'\n' read -d '' -r -a file_array <<< "$FILES"

for f in "${file_array[@]}"; do
    if [ ! -r "$f" ]; then
        show_error "Cannot read file: $(basename "$f")"
        exit 1
    fi
done

# Launch the GTK app directly with all selected files as positional args.
# gui.py uses Gio.ApplicationFlags.HANDLES_OPEN, so files are loaded via do_open().
"$PYTHON_CMD" "$FILE_CONVERTER_PATH" "${file_array[@]}" &
disown

exit 0
FM_SCRIPT_EOF
    sed -i "s|FILE_CONVERTER_PATH_PLACEHOLDER|$FILE_CONVERTER_SCRIPT|g" "$tmpscript"

    local installed_any=false
    for fm in nautilus nemo; do
        if ! command_exists "$fm"; then
            continue
        fi
        local scripts_dir
        case "$fm" in
            nautilus) scripts_dir="$NAUTILUS_SCRIPT_DIR" ;;
            nemo)     scripts_dir="$NEMO_SCRIPT_DIR" ;;
        esac
        mkdir -p "$scripts_dir"
        local target="$scripts_dir/Convert with File Converter"
        cp "$tmpscript" "$target"
        chmod +x "$target"
        print_success "Right-click script installed for $fm: $target"
        installed_any=true
        if pgrep -x "$fm" >/dev/null; then
            print_status "Restarting $fm to load the new script..."
            "$fm" -q 2>/dev/null || true
        fi
    done
    rm -f "$tmpscript"

    if [ "$installed_any" = false ]; then
        print_warning "Neither Nautilus nor Nemo found. Skipping right-click script."
    fi
}

# Install the context-aware "Convert to ▸" submenu via nautilus-python /
# nemo-python. Symlinking (vs copying) lets edits to the extension propagate
# after a file manager restart and lets the extension locate the project via
# os.path.realpath(__file__).
setup_fm_extension() {
    print_status "Installing right-click submenu extension..."

    if [ ! -f "$EXTENSION_SRC" ]; then
        print_warning "Extension source not found at $EXTENSION_SRC; skipping."
        return
    fi

    local installed_any=false

    if command_exists nautilus; then
        if python3 -c "import gi; gi.require_version('Nautilus','4.0')" 2>/dev/null \
           || python3 -c "import gi; gi.require_version('Nautilus','3.0')" 2>/dev/null; then
            mkdir -p "$NAUTILUS_EXTENSION_DIR"
            ln -sf "$EXTENSION_SRC" "$NAUTILUS_EXTENSION_LINK"
            print_success "Extension symlinked for Nautilus: $NAUTILUS_EXTENSION_LINK"
            installed_any=true
            pgrep -x nautilus >/dev/null && nautilus -q 2>/dev/null || true
        else
            print_warning "Nautilus found but python3-nautilus missing — sudo apt install python3-nautilus"
        fi
    fi

    if command_exists nemo; then
        if python3 -c "import gi; gi.require_version('Nemo','3.0')" 2>/dev/null; then
            mkdir -p "$NEMO_EXTENSION_DIR"
            ln -sf "$EXTENSION_SRC" "$NEMO_EXTENSION_LINK"
            print_success "Extension symlinked for Nemo: $NEMO_EXTENSION_LINK"
            installed_any=true
            pgrep -x nemo >/dev/null && nemo -q 2>/dev/null || true
        else
            print_warning "Nemo found but nemo-python missing — sudo apt install nemo-python"
        fi
    fi

    if [ "$installed_any" = false ]; then
        print_warning "No supported file manager found. Skipping submenu extension."
    fi
}

# Setup desktop entry
setup_desktop_entry() {
    print_status "Setting up desktop entry..." 
    
    # Create applications directory
    APPLICATIONS_DIR="$HOME/.local/share/applications" 
    mkdir -p "$APPLICATIONS_DIR" 
    
    # Create desktop entry
    DESKTOP_ENTRY="$APPLICATIONS_DIR/file-converter.desktop" 
    
    cat > "$DESKTOP_ENTRY" << DESKTOP_ENTRY_EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=File Converter
GenericName=Document Converter
Comment=Convert files between various formats using pandoc and LibreOffice
Exec=python3 $FILE_CONVERTER_SCRIPT %F
Icon=document-properties
Terminal=false
StartupNotify=true
NoDisplay=false
Categories=Office;Utility;TextEditor;

MimeType=text/markdown;text/plain;text/html;application/pdf;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.oasis.opendocument.text;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;application/vnd.oasis.opendocument.spreadsheet;application/vnd.openxmlformats-officedocument.presentationml.presentation;application/vnd.oasis.opendocument.presentation;application/msword;application/rtf;application/epub+zip;text/x-tex;text/x-rst;

Keywords=convert;document;pdf;markdown;word;html;epub;
DESKTOP_ENTRY_EOF
    
    print_success "Desktop entry created: $DESKTOP_ENTRY" 
    
    # Update desktop database
    if command_exists update-desktop-database; then 
        update-desktop-database "$APPLICATIONS_DIR" 
        print_success "Desktop database updated" 
    fi
} 

# Setup file associations
setup_file_associations() {
    print_status "Setting up file associations..." 
    
    # Create mimeapps.list entry
    MIMEAPPS_FILE="$HOME/.config/mimeapps.list" 
    
    # Backup existing file
    if [ -f "$MIMEAPPS_FILE" ]; then 
        cp "$MIMEAPPS_FILE" "$MIMEAPPS_FILE.backup.$(date +%Y%m%d_%H%M%S)" 
        print_status "Backed up existing mimeapps.list" 
    fi
    
    # Add File Converter associations
    mkdir -p "$(dirname "$MIMEAPPS_FILE")" 
    
    if [ ! -f "$MIMEAPPS_FILE" ]; then 
        # Create new file
        cat > "$MIMEAPPS_FILE" << 'MIMEAPPS_EOF'
[Added Associations]
text/markdown=file-converter.desktop;
text/plain=file-converter.desktop;
text/html=file-converter.desktop;
application/pdf=file-converter.desktop;
application/vnd.openxmlformats-officedocument.wordprocessingml.document=file-converter.desktop;
application/vnd.oasis.opendocument.text=file-converter.desktop;
application/msword=file-converter.desktop;
application/rtf=file-converter.desktop;
application/epub+zip=file-converter.desktop;
text/x-tex=file-converter.desktop;
text/x-rst=file-converter.desktop;

[Default Applications]

[Removed Associations]
MIMEAPPS_EOF
    else
        # Add to existing file
        print_status "Adding File Converter associations to existing mimeapps.list..." 
        
        # Check if [Added Associations] section exists
        if ! grep -q "^\[Added Associations\]" "$MIMEAPPS_FILE"; then 
            echo "" >> "$MIMEAPPS_FILE"
            echo "[Added Associations]" >> "$MIMEAPPS_FILE"
        fi
        
        # Add our associations after [Added Associations] section
        local associations=(
            "text/markdown=file-converter.desktop;"
            "text/plain=file-converter.desktop;"
            "text/html=file-converter.desktop;"
            "application/pdf=file-converter.desktop;"
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document=file-converter.desktop;"
            "application/vnd.oasis.opendocument.text=file-converter.desktop;"
            "application/msword=file-converter.desktop;"
            "application/rtf=file-converter.desktop;"
            "application/epub+zip=file-converter.desktop;"
            "text/x-tex=file-converter.desktop;"
            "text/x-rst=file-converter.desktop;"
        )
        
        for assoc in "${associations[@]}"; do
            # Only add if not already present
            if ! grep -q "$assoc" "$MIMEAPPS_FILE"; then 
                # Find the [Added Associations] section and add after it
                sed -i "/^\[Added Associations\]/a $assoc" "$MIMEAPPS_FILE"
            fi
        done
    fi
    
    print_success "File associations configured" 
} 

# Setup command-line access
setup_command_line_access() {
    print_status "Setting up command-line access..." 
    
    # Create bin directory if it doesn't exist
    BIN_DIR="$HOME/.local/bin" 
    mkdir -p "$BIN_DIR" 
    
    # Create symlink
    FILE_CONVERTER_LINK="$BIN_DIR/file-converter" 
    
    if [ -L "$FILE_CONVERTER_LINK" ]; then 
        rm "$FILE_CONVERTER_LINK"
    fi
    
    ln -s "$FILE_CONVERTER_SCRIPT" "$FILE_CONVERTER_LINK" 
    print_success "Command-line link created: $FILE_CONVERTER_LINK" 
    
    # Check if ~/.local/bin is in PATH
    if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then 
        print_warning "~/.local/bin is not in your PATH" 
        print_status "Adding to ~/.bashrc..." 
        
        if ! grep -q 'export PATH="$HOME/.local/bin:$PATH"' "$HOME/.bashrc"; then 
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
            print_success "Added ~/.local/bin to PATH in ~/.bashrc" 
            print_warning "Please restart your terminal or run: source ~/.bashrc" 
        fi
    fi
} 

# Test the installation
test_installation() {
    print_status "Testing installation..." 
    
    # Test File Converter script (syntax check only — GUI app has no --version flag)
    if python3 -m py_compile "$FILE_CONVERTER_SCRIPT" >/dev/null 2>&1; then
        print_success "File Converter script: OK"
    else
        print_error "File Converter script: FAILED"
    fi
    
    # Test right-click script for each present file manager
    for fm in nautilus nemo; do
        if ! command_exists "$fm"; then continue; fi
        case "$fm" in
            nautilus) script="$NAUTILUS_SCRIPT_DIR/Convert with File Converter";  link="$NAUTILUS_EXTENSION_LINK" ;;
            nemo)     script="$NEMO_SCRIPT_DIR/Convert with File Converter";      link="$NEMO_EXTENSION_LINK" ;;
        esac
        if [ -x "$script" ]; then
            print_success "${fm^} right-click script: OK"
        else
            print_warning "${fm^} right-click script: Not found or not executable"
        fi
        if [ -L "$link" ] && [ -e "$link" ]; then
            print_success "${fm^} submenu extension: OK"
        else
            print_warning "${fm^} submenu extension: Not installed"
        fi
    done
    
    # Test desktop entry
    if [ -f "$HOME/.local/share/applications/file-converter.desktop" ]; then 
        print_success "Desktop entry: OK" 
    else
        print_warning "Desktop entry: Not found" 
    fi
    
    # Test command-line access
    if [ -L "$HOME/.local/bin/file-converter" ]; then 
        print_success "Command-line access: OK" 
    else
        print_warning "Command-line access: Not found" 
    fi
} 

# Main setup function
main() {
    echo "=========================================="
    echo "File Converter GUI Integration Setup - Version 4.1" 
    echo "=========================================="
    echo "Setting up file manager integration"
    echo "=========================================="
    echo

    # Check if running as root
    if [[ $EUID -eq 0 ]]; then 
        print_error "Please run this script as a regular user (not root)" 
        exit 1
    fi

    # Detect desktop environment
    DESKTOP=$(detect_desktop) 
    print_status "Detected desktop environment: $DESKTOP" 

    # Check if File Converter script exists
    if [ ! -f "$FILE_CONVERTER_SCRIPT" ]; then 
        print_error "File Converter script not found at: $FILE_CONVERTER_SCRIPT" 
        print_error "Please ensure File Converter is properly installed" 
        exit 1
    fi

    # Check if File Converter script is executable
    if [ ! -x "$FILE_CONVERTER_SCRIPT" ]; then 
        print_status "Making File Converter script executable..." 
        chmod +x "$FILE_CONVERTER_SCRIPT" 
    fi

    # Test File Converter script (syntax check — GUI app has no --version flag)
    print_status "Testing File Converter script..."
    if python3 -m py_compile "$FILE_CONVERTER_SCRIPT" >/dev/null 2>&1; then
        print_success "File Converter script is working"
    else
        print_error "File Converter script is not working properly"
        exit 1
    fi

    # Check for required GUI tools
    print_status "Checking GUI dependencies..." 
    
    # Note: this script must NOT be run with sudo (the EUID check above rejects root).
    # The blocks below call sudo only when a needed package is missing. If you followed
    # the README's apt install line they're all no-ops and no password prompt appears.

    if ! command_exists zenity; then
        print_status "Installing zenity for GUI dialogs..."
        sudo apt update
        sudo apt install -y zenity
    fi

    # File-manager Python bindings (required for the context-aware submenu) and
    # notify-send (used by the extension to report conversion results). Install
    # python3-nautilus / nemo-python only when the matching file manager is on
    # the system, so headless or single-FM machines don't pull in dead weight.
    # Note: GNOME's package follows the python3-* convention; Cinnamon's keeps
    # the older nemo-python name. Don't homogenize — both ship the same gi binding.
    if command_exists nautilus && ! dpkg -s python3-nautilus >/dev/null 2>&1; then
        print_status "Installing python3-nautilus for right-click submenu..."
        sudo apt update
        sudo apt install -y python3-nautilus
    fi
    if command_exists nemo && ! dpkg -s nemo-python >/dev/null 2>&1; then
        print_status "Installing nemo-python for right-click submenu..."
        sudo apt update
        sudo apt install -y nemo-python
    fi
    if ! command_exists notify-send; then
        print_status "Installing libnotify-bin for desktop notifications..."
        sudo apt install -y libnotify-bin
    fi

    # File manager integration — installed for each detected file manager.
    if command_exists nautilus || command_exists nemo; then
        setup_fm_integration
        setup_fm_extension
    else
        print_warning "Neither Nautilus nor Nemo detected. Skipping right-click integration."
    fi

    # Setup desktop entry
    setup_desktop_entry 

    # Setup file associations
    setup_file_associations 

    # Create symbolic link for command-line access
    setup_command_line_access 

    # Test the installation
    test_installation 

    echo
    echo "=========================================="
    echo "File Converter GUI Integration Setup Complete!" 
    echo "=========================================="
    echo
    print_success "Available integration methods:" 
    echo " ✓ Right-click menu in Nautilus file manager"
    echo " ✓ Desktop application entry"
    echo " ✓ File associations for supported formats"
    echo " ✓ Command-line access via 'file-converter' command"
    echo
    print_status "How to use:" 
    echo " • Right-click any supported file in Nautilus → Scripts → Convert with File Converter"
    echo " • Double-click supported files to open with File Converter"
    echo " • Search for 'File Converter' in your application menu"
    echo " • Run 'file-converter' command in terminal"
    echo
    print_status "Supported file types:" 
    echo " • Documents: .md, .html, .docx, .odt, .pdf, .txt, .doc, .rtf"
    echo " • Spreadsheets: .xlsx, .xls, .ods, .csv"
    echo " • Presentations: .pptx, .ppt, .odp"
    echo " • Other: .epub, .tex, .rst"
    echo
    print_success "Setup completed successfully!" 
} 

# Show usage if help requested
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then 
    echo "File Converter GUI Integration Setup Script"
    echo "Usage: $0 [options]"
    echo
    echo "Options:"
    echo "  --help, -h     Show this help message"
    echo "  --uninstall    Remove GUI integration"
    echo
    echo "This script sets up GUI integration for File Converter including:"
    echo "  • Nautilus right-click menu integration"
    echo "  • Desktop application entry"
    echo "  • File associations"
    echo "  • Command-line access"
    exit 0
fi

# Uninstall option
if [ "$1" = "--uninstall" ]; then 
    print_status "Removing File Converter GUI integration..." 
    
    # Remove right-click scripts and submenu extension symlinks (Nautilus + Nemo)
    rm -f "$NAUTILUS_SCRIPT_DIR/Convert with File Converter"
    rm -f "$NEMO_SCRIPT_DIR/Convert with File Converter"
    rm -f "$NAUTILUS_EXTENSION_LINK"
    rm -f "$NEMO_EXTENSION_LINK"
    
    # Remove desktop entry
    rm -f "$HOME/.local/share/applications/file-converter.desktop" 
    
    # Remove command-line link
    rm -f "$HOME/.local/bin/file-converter" 
    
    # Update desktop database
    if command_exists update-desktop-database; then 
        update-desktop-database "$HOME/.local/share/applications" 
    fi
    
    print_success "File Converter GUI integration removed" 
    exit 0
fi

# Run main function
main "$@"
